### ISSUE TITLE
[Write Content] Add content to resource library for Front End Developers

### ISSUE THREAD

**Issue by RitikPatni** [RitikPatni/Front-End-Web-Developer-Path#6]
I created this repository a while back so that people can look for front-end development tools or design inspirations here but since then I made no progress in making it more expressive.So now I need some help to make the content more descriptive so that later this content can be used by more people easily.

Any kind of Help will be appreciated
**Thanks for taking a look**

**Comment by tushgup** [comment]
Hey, so basically you want to add a bit of context to each type of resource? I think I can help!

**Comment by RitikPatni** [comment]
@tushgup If you can add context to each resource or even each category then it would be helpful to me

**Comment by tushgup** [comment]
Alright perfect, will get on it! 👍

**Comment by murphytrueman** [comment]
Hi @ritikpatni, are you looking to have a brief description of each link and each category added? Am happy to help with this, as well as add additional resources that might be missing. Let me know, can jump on this asap!

**Comment by RitikPatni** [comment]
@murphytrueman Exactly adding more resources would be even better

**Comment by murphytrueman** [comment]
@RitikPatni sure, sounds good. I'll see what I can put together :)

**Comment by Adroit11** [comment]
Would also like to jump on this
